
INTENT_EXAMPLES = {
    "greet": [
        "hi",
        "hello",
        "hey",
        "hey!",
        "good morning",
        "good afternoon",
        "good evening",
        "yo",
        "hey there",
        "hi there",
        "hello there",
        "hey bot",
        "hi bot",
        "hello bot",
        "hiya",
        "howdy",
        "sup",
        "what's up",
        "good day",
        "greetings",
        "morning",
        "afternoon",
        "evening",
    ],
    "goodbye": [
        "bye",
        "goodbye",
        "see you",
        "talk to you later",
        "catch you later",
        "see ya",
        "see you later",
        "talk later",
        "bye bye",
        "good night",
        "have a good day",
        "have a nice day",
        "thanks bye",
        "that's all thanks",
        "thanks, goodbye",
        "later",
        "i'm done",
        "i have to go",
        "see you soon",
        "until next time",
        "ok bye",
    ],
    "business_hours": [
        "what time do you open",
        "when do you close",
        "what are your opening hours",
        "what time are you open until",
        "are you open now",
        "what are your operating hours",
        "what time does the shop open",
        "what are your business hours",
        "what are your hours today",
        "are you open on weekends",
        "are you open on sunday",
        "are you open on saturday",
        "what time do you open today",
        "what time do you close today",
        "when are you open",
        "what time do you start business",
        "what time do you end business",
        "are you open late",
        "are you open 24 hours",
        "opening times",
        "closing time",
        "hours of operation",
        "do you open on public holidays",
    ],
    "location": [
        "where are you located",
        "what is your address",
        "where is your shop",
        "how do I get there",
        "where is the restaurant",
        "what is your location",
        "what's your address",
        "where can I find you",
        "where are you based",
        "what is your exact location",
        "how do i reach you",
        "how to get to your place",
        "directions to your shop",
        "where is your office",
        "where is your store",
        "where are you",
        "share your address",
        "location please",
        "address please",
        "where are you situated",
    ],
    "pricing": [
        "how much does it cost",
        "what are your prices like",
        "do you have a price list",
        "what is the fee",
        "how much is the course",
        "what is the average price",
        "what are your rates",
        "how much is it",
        "how much do you charge",
        "what's the price",
        "what is your price",
        "pricing details",
        "price range",
        "what are the charges",
        "is it expensive",
        "what does it cost",
        "how much for a booking",
        "how much for a table",
        "is there a fee",
        "is there a membership fee",
        "what are your fees",
        "what is the cost per session",
        "what is the cost per appointment",
    ],
    # Restaurant-specific
    "menu": [
        "what do you serve",
        "what's on the menu",
        "menu please",
        "do you have a menu",
        "what food do you offer",
        "what dishes do you have",
        "what are your specialties",
        "do you have any signature dishes",
        "what cuisine do you serve",
        "what kind of food is this",
        "can i see the menu",
        "what's your menu like",
        "what are the house specials",
        "what is your specialty",
        "any chef's specials",
        "what can i order",
        "do you have vegetarian options",
        "do you have halal options",
        "do you have vegan options",
        "any gluten free options",
    ],
    "dining_options": [
        "do you offer delivery",
        "is there takeaway",
        "can i dine in",
        "do you have dine in",
        "do you offer takeaway",
        "do you deliver",
        "what are your dining options",
        "can i order for delivery",
        "do you have pickup",
        "can i take away",
        "is pickup available",
        "do you have curbside pickup",
        "do you do self-collection",
        "is delivery available",
        "can i eat at the restaurant",
        "do you allow dine-in",
        "do you provide dine in service",
        "is dine in available",
        "can i sit in",
        "do you allow eat in",
        "do you have in-store dining",
        "is takeaway available",
        "do you offer takeaway service",
        "can i pick up my order",
        "is pickup allowed",
        "can i order for pickup",
        "do you offer delivery and takeaway",
        "are delivery and pickup available",
    ],
    "reservation": [
        "can i make a reservation",
        "do you take reservations",
        "can i reserve a table",
        "is reservation required",
        "do you accept reservations",
        "how do i reserve a table",
        "can i book a table online",
        "is booking required",
        "can i book for tonight",
        "can i reserve for two",
        "can i make a table booking",
        "table reservation",
        "can i reserve a seat",
        "do i need to book a table",
        "can i make a dinner reservation",
        "can i book for tomorrow",
        "reserve a table for tonight",
        "book a table for two",
        "can i reserve a table by phone",
        "how do i book a reservation",
        "is there a reservation link",
    ],
    "booking": [
        "i want to make a booking",
        "can i reserve a table",
        "i want to book a slot",
        "can i book an appointment",
        "i want to make a reservation",
        "can i book a table",
        "how do i reserve",
        "i want to reserve",
        "can i make a booking",
        "i need a reservation",
        "book me a table",
        "book an appointment",
        "book a slot for me",
        "how can i book",
        "i want to schedule a visit",
        "can i schedule a visit",
        "i want to schedule an appointment",
        "i'd like to make a booking",
        "i'd like to reserve a table",
        "can i make a reservation",
        "book a seat",
        "make a booking for tonight",
        "reserve for two",
    ],
    "contact_support": [
        "how can i contact you",
        "what is your email",
        "how do i reach support",
        "is there a phone number",
        "who can i talk to",
        "how can i contact customer service",
        "how do i contact support",
        "i need to contact you",
        "how can i get in touch",
        "can i get your phone number",
        "what's your phone number",
        "what's your email",
        "email address please",
        "phone number please",
        "contact details",
        "support contact",
        "help desk contact",
        "who do i email",
        "who do i call",
        "how can i reach you",
        "how do i talk to someone",
    ],
    # Education-specific
    "courses": [
        "what courses do you offer",
        "what programs are available",
        "list your courses",
        "what can i study",
        "what are your programs",
        "do you have short courses",
        "do you offer diploma courses",
        "do you have degree programs",
        "what classes can i take",
        "what subjects do you teach",
        "what modules are offered",
        "course list",
        "program list",
        "what courses are open",
    ],
    "intake": [
        "when is the next intake",
        "what are the intake dates",
        "when can i enroll",
        "when do classes start",
        "next intake period",
        "upcoming intakes",
        "when is the next enrollment",
        "intake schedule",
        "enrollment dates",
        "registration dates",
        "when does the term start",
        "next semester intake",
    ],
    "apply": [
        "how do i apply",
        "where can i apply",
        "application process",
        "how to enroll",
        "how to register",
        "application link",
        "how do i sign up",
        "how can i enroll",
        "how do i submit an application",
        "where is the application form",
        "how do i register for a course",
        "how do i apply online",
        "where can i submit my application",
        "application instructions",
        "how to apply for admission",
        "admission application",
        "how to sign up for classes",
        "enrollment process",
        "application steps",
    ],
    "delivery_mode": [
        "is it online",
        "do you offer online classes",
        "is it in person",
        "do you have hybrid classes",
        "what is the delivery mode",
        "are classes online or onsite",
        "is there a hybrid option",
        "do you have weekend classes",
        "is it face to face",
        "do you offer virtual classes",
        "online or in-person",
        "onsite classes available",
        "is it virtual",
        "are classes remote",
        "do you offer blended learning",
        "what learning mode do you offer",
    ],
    # Retail-specific
    "products": [
        "what do you sell",
        "what products do you have",
        "what items do you carry",
        "what categories do you sell",
        "what is your product range",
        "what do you stock",
        "what items are available",
        "what do you offer",
        "do you sell electronics",
        "do you sell clothing",
        "do you sell accessories",
        "what can i buy",
    ],
    "delivery": [
        "do you offer delivery",
        "what are your delivery options",
        "how long is shipping",
        "delivery info",
        "do you ship",
        "do you ship overseas",
        "how much is delivery",
        "shipping options",
        "delivery time",
        "shipping time",
        "do you have express shipping",
        "do you deliver to my area",
        "what are the shipping fees",
        "how long does delivery take",
        "is same day delivery available",
        "do you offer free shipping",
        "can i choose delivery slots",
        "do you have next day delivery",
        "do you deliver internationally",
    ],
    "returns": [
        "what is your return policy",
        "can i return an item",
        "returns policy",
        "how do returns work",
        "refund policy",
        "do you accept returns",
        "can i get a refund",
        "how do i return",
        "return process",
        "exchange policy",
        "can i exchange this",
        "how long is the return window",
        "what is your refund process",
        "can i return a product",
        "return instructions",
        "is there a restocking fee",
        "can i return online purchases",
        "how do i exchange an item",
    ],
    "warranty": [
        "do you offer warranty",
        "warranty information",
        "how long is the warranty",
        "is there a warranty",
        "warranty details",
        "does it come with warranty",
        "what's the warranty period",
        "do you provide warranty",
        "is warranty included",
        "is there a guarantee",
        "how many months warranty",
        "does it include guarantee",
        "warranty coverage",
        "is warranty covered",
        "what is covered under warranty",
    ],
    "payment_methods": [
        "how can i pay",
        "what payment methods do you accept",
        "do you take credit card",
        "can i pay by cash",
        "payment options",
        "do you accept paypal",
        "do you accept paynow",
        "can i pay by debit card",
        "do you accept bank transfer",
        "how do i pay",
        "do you accept visa",
        "do you accept mastercard",
        "can i pay by card",
        "what cards do you accept",
        "do you take apple pay",
        "do you take google pay",
        "is cash accepted",
    ],
    "fallback": [
        "i dont know",
        "random question",
        "can you help me",
        "what is this",
        "i am confused",
        "i'm not sure",
        "i don't understand",
        "that doesn't make sense",
        "huh",
        "what do you mean",
        "i need help",
        "can you explain",
        "i have a question",
        "something else",
        "not what i want",
        "that's not it",
        "no idea",
        "i'm lost",
        "can you clarify",
        "i don't get it",
    ],
}
