
INTENT_EXAMPLES = {
    "greet": [
        "hi",
        "hello",
        "hey",
        "good morning",
        "good afternoon",
        "yo",
        "hey there",
    ],
    "goodbye": [
        "bye",
        "goodbye",
        "see you",
        "talk to you later",
        "catch you later",
    ],
    "business_hours": [
        "what time do you open",
        "when do you close",
        "what are your opening hours",
        "what time are you open until",
        "are you open now",
        "what are your operating hours",
        "what time does the shop open",
        "what are your business hours",
    ],
    "location": [
        "where are you located",
        "what is your address",
        "where is your shop",
        "how do I get there",
        "where is the restaurant",
        "what is your location",
    ],
    "pricing": [
        "how much does it cost",
        "what are your prices like",
        "do you have a price list",
        "what is the fee",
        "how much is the course",
        "what is the average price",
        "what are your rates",
    ],
    "booking": [
        "i want to make a booking",
        "can i reserve a table",
        "i want to book a slot",
        "can i book an appointment",
        "i want to make a reservation",
        "can i book a table",
        "how do i reserve",
    ],
    "contact_support": [
        "how can i contact you",
        "what is your email",
        "how do i reach support",
        "is there a phone number",
        "who can i talk to",
        "how can i contact customer service",
    ],
    "fallback": [
        "i dont know",
        "random question",
        "can you help me",
        "what is this",
        "i am confused",
    ],
}
